### ISSUE TITLE
Question: Service Workers

### ISSUE THREAD

**Issue by erikrenz88** [coatless-quarto/r-shinylive-demo#12]
I noticed your comments on the service workers not being uploaded and I have been trying to troubleshoot my way through this. I have tried to add the resource explicitly numerous times including:

- top of the .qmd I'm using
```
format:
  html:
    resources:
      - shinylive-sw.js
      
filters:
  - shinylive
```
- in the _quarto.yml file
```
project:
  type: website
  resources: 
    - shinylive-sw.js
```

I still get the error in my web browser that the service worker cannot be found. Were there any other suggestions on what to try? Or do you know anything about this being added to the v1.5 milestone? I know you logged the original issue and they assigned it to the milestone but wasn't sure if I missed any updated on that.

Thanks for your walkthrough! It's been very useful.
